name: Build MacOS CLI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install cmake make libomp
      - name: Compile CLI
        run: |
          mkdir build && cd build
          cmake .. -DCLI=1
          cmake --build .
      - name: Test run
        run: |
          cd build
          cp ../CrystalDatabase.txt ./
          cp ../Source/BuildResources/test_input.txt ./
          ./LightwaveExplorer test_input.txt
      - name: Prepare distribution
        run: |
          mkdir dist
          cp build/LightwaveExplorer dist/LightwaveExplorerMacCLI
          cp CrystalDatabase.txt dist/
          cp Source/BuildResources/DefaultValues.ini dist/ || true
      - name: Upload Mac CLI
        uses: actions/upload-artifact@v4
        with:
          name: LightwaveExplorer-CLI-Mac
          path: dist/
      - name: Release Mac CLI
        uses: softprops/action-gh-release@v1
        with:
          files: dist/LightwaveExplorerMacCLI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
